Base layout
PAWII-Portal-Loker/frontend pull request #11
Opened 2024-12-04 15:23 UTC by Rendy752

2024-12-13 13:33 UTC, fanesz requested changes

2024-12-13 13:33 UTC, fanesz commented on src/common/utils/navbar.ts
> +import { useState, useEffect } from "react";
move this to src/common/hooks/useXXX.ts, because its a custom hooks and have a state/reactive.

2024-12-13 13:33 UTC, fanesz commented on src/common/utils/validImageUrl.ts
> +    url.startsWith("/")
how come url is starts with "/"?

2024-12-13 13:33 UTC, fanesz commented on src/components/containers/dropdown.tsx
> +}: DropdownProps) => {
to make it more readible, i prefer like this:
```ts
const Dropdown = (props: DropdownProps) => {
  // using object descruction
  const { items, name = "Item", isLoading = false, isAlwaysFullWidth = false } = props;
}
```

2024-12-13 13:33 UTC, fanesz commented on src/components/containers/dropdown.tsx
> +}: DropdownProps) => {
also if possible, remove unnecessary default variable on that name/isLoading/isAlwaysFullWidth

2024-12-13 13:33 UTC, fanesz commented on src/components/containers/loadingCard.tsx
> +      <div className="w-full h-[200px] bg-gray-200 mb-3 rounded-lg"></div>
```suggestion
      <div className="w-full h-[200px] bg-gray-200 mb-3 rounded-lg" />
```

2024-12-13 13:33 UTC, fanesz commented on src/components/containers/roleCardPicker.tsx
> +}: RoleCardPickerProps) => {
same as prev comments, use object descruction

2024-12-13 13:33 UTC, fanesz commented on src/components/layouts/footer.tsx
> +        <p>© {new Date().getFullYear()} PortalLoker. All rights reserved</p>
use moment

2024-12-13 13:33 UTC, fanesz commented on src/components/layouts/loginDialog.tsx
> +            Don&apos;t have an account?{" "}
i think there is a direct symbol that u can use rather than using something like `&apos;`

2024-12-13 13:33 UTC, fanesz commented on src/components/layouts/loginDialog.tsx
> +                      : "focus:ring-red-500",
is this have a possibility to be a repetitive code,
maybe u can create a handler function that return that css, so it gonna be look like this:
```js
clsx("css.....", handlerErrorRing(!errors[field.name]));
```
or something more simple

2024-12-13 13:33 UTC, fanesz commented on src/components/layouts/loginDialog.tsx
> +                  : "hover:bg-blue-400 transition-all duration-200",
similar as error ring before, because less ternary logic on component codes = better looks

2024-12-13 13:33 UTC, fanesz commented on src/components/layouts/navbar.tsx
> +  const { isNavigationOpen, setIsNavigationOpen, setIsLoginDialogOpen } =
for this state naming, i think it better to be like this:
~setIsNavigationOpen~ setNavigationOpen
~setIsLoginDialogOpen~ setLoginDialogOpen

2024-12-13 13:33 UTC, fanesz commented on src/components/layouts/registerDialog.tsx
> +import { CreateUserField } from "@/contexts/user/fields/create";
create an alias import for each contexts similar like this:
https://github.com/PAWII-Portal-Loker/backend/blob/master/tsconfig.json

so it have a better looks:
```js
import { CreateUserDto } from "@user/types/create";
import { CreateUserSchema } from "@user/schemas/create";
import { CreateUserField } from "@user/fields/create";
```

2024-12-13 13:33 UTC, fanesz commented on src/components/layouts/roleDialog.tsx
> +  }, [getLastEducationTypes]);
remove deps

2024-12-13 13:33 UTC, fanesz commented on src/contexts/(company)/service.ts
> +    }
try:
```suggestion
    callback.onFullfilled?.();
```

2024-12-14 07:23 UTC, Rendy752 commented on src/app/layout.tsx
> +    }, 60000);
periodic check login status for expired auth session

2024-12-14 07:35 UTC, Rendy752 commented on src/app/vacancy/[id]/page.tsx
> +    <div>
maybe yes, maybe no, layout not completed yet

2024-12-14 07:36 UTC, Rendy752 commented on src/app/vacancy/page.tsx
> +"use client";
yes, for now

2024-12-14 08:09 UTC, Rendy752 commented on src/common/utils/validImageUrl.ts
> +    url.startsWith("/")
owh yeah

2024-12-16 13:29 UTC, fanesz commented on src/app/layout.tsx
> +    }, 60000);
move to different issue [#14](https://github.com/PAWII-Portal-Loker/frontend/issues/14), set priority to low

2024-12-16 13:33 UTC, fanesz approved these changes

2024-12-16 13:33 UTC, merged

2024-12-16 13:34 UTC, fanesz commented
deprior auth issue with device id generator [#14](https://github.com/PAWII-Portal-Loker/frontend/issues/14), focus on layout